<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Win32Interop</RootNamespace>
    <Configurations>Debug;Documentation;Release</Configurations>
    <PostBuildEvent>copy "$(SolutionDir)SystemHookCore\$(ConfigurationName)\SystemHookCore.dll" "$(TargetDir)"
Exit /b 0</PostBuildEvent>
    <AssemblyTitle>Win32Interop.User32</AssemblyTitle>
    <Description>Interop methods, structs, and enums for user32.dll</Description>
    <Company>Shane Clark</Company>
    <Product>Win32Interop.User32</Product>
    <Copyright>Copyright © 2025</Copyright>
    <AssemblyVersion>2.0.0</AssemblyVersion>
    <FileVersion>2.0.0</FileVersion>
    <Platforms>AnyCPU;x64</Platforms>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DocumentationFile>bin\Debug\Win32Interop.User32.XML</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <DocumentationFile>bin\Debug\Win32Interop.User32.XML</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DocumentationFile>bin\Release\Win32Interop.User32.XML</DocumentationFile>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <DocumentationFile>bin\Release\Win32Interop.User32.XML</DocumentationFile>
  </PropertyGroup>
</Project>