<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>Win32Interop</RootNamespace>
    <Configurations>Debug;Documentation;Release</Configurations>
    <AssemblyTitle>Win32Interop.Uxtheme</AssemblyTitle>
    <Description>Interop methods, structs, and enums for uxtheme.dll</Description>
    <Company>Luke Stratman</Company>
    <Product>Win32Interop.Uxtheme</Product>
    <Copyright>Copyright © 2013</Copyright>
    <AssemblyVersion>1.0.1</AssemblyVersion>
    <FileVersion>1.0.1</FileVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Gdi32\Win32Interop.Gdi32.csproj" />
    <ProjectReference Include="..\User32\Win32Interop.User32.csproj" />
  </ItemGroup>
</Project>